# Generated by Django 4.2.2 on 2023-06-30 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('api_url', models.URLField(validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(100)])),
                ('documentation_url', models.URLField()),
                ('auth_required', models.BooleanField()),
                ('additional_info', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
