# Generated by Django 4.2.11 on 2024-04-26 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieActor',
            new_name='movie_actor',
        ),
    ]
